apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: clo835-cluster
  region: us-east-1
  version: "1.29"
nodeGroups:
  - name: ng-clo835
    instanceType: t3.medium
    desiredCapacity: 2
    volumeSize: 20
    ssh:
      allow: true
      publicKeyName: clo835-key
iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: clo835
        namespace: final
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
