---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: group6-final-project-eks
  region: "us-east-1"
  version: "1.29"

availabilityZones: ["us-east-1a" ,"us-east-1b" ,"us-east-1c"]
iam:
  serviceRoleARN: arn:aws:iam::860572194478:role/LabRole
addons:
    - name: aws-ebs-csi-driver
managedNodeGroups:
- name: nodegroup
  desiredCapacity: 2
  instanceType: t3.small
  ssh:
    enableSsm: true
  iam:
    instanceRoleARN: arn:aws:iam::860572194478:role/LabRole
