apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: final
  labels:
    app: flask
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      serviceAccountName: clo835
      containers:
      - name: flask
        image: 860572194478.dkr.ecr.us-east-1.amazonaws.com/webapp-repo:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 81
        env:
        - name: HEADER_NAME
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: HEADER_NAME
        - name: BACKGROUND_IMAGE_URL
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: BACKGROUND_IMAGE_URL
        - name: S3_BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: S3_BUCKET_NAME
        - name: S3_OBJECT_KEY
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: S3_OBJECT_KEY
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: AWS_REGION
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_SESSION_TOKEN
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: AWS_SESSION_TOKEN
        - name: DBHOST
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: DBHOST
        - name: DBPORT
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: DBPORT
        - name: DATABASE
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD

        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"

        livenessProbe:
          httpGet:
            path: /
            port: 81
          initialDelaySeconds: 30
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /
            port: 81
          initialDelaySeconds: 5
          periodSeconds: 5

      imagePullSecrets:
        - name: ecr-secret
