apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: final
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      serviceAccountName: ebs-access-sa
      containers:
        - name: mysql
          image: 860572194478.dkr.ecr.us-east-1.amazonaws.com/mysql-repo:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
      imagePullSecrets:
        - name: ecr-secret
      volumes:
      - name: data
        persistentVolumeClaim:        
          claimName: mysql-pvc
