apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: final
spec:
  serviceName: "mysql"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: 813634909417.dkr.ecr.us-east-1.amazonaws.com/mysql-repo:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      imagePullSecrets:
        - name: ecr-secret
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
