apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: final
type: Opaque
data:
  MYSQL_USER: bXlzcWw=           # base64 encoded value of 'mysql'
  MYSQL_PASSWORD: bXlzcWxwYXNz    # base64 encoded value of 'mysqlpass' 