apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: final
type: Opaque
data:
  MYSQL_USER: c3FsdXNlcg==         # base64 for 'sqluser'
  MYSQL_PASSWORD: cGFzc3dvcmQ=     # base64 for 'password'
