apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: final
type: Opaque
data:
  MYSQL_USER: cm9vdA==           # base64 of "root"
  MYSQL_PASSWORD: cGFzc3dvcmQ=   # base64 of "password"
