apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: final
type: Opaque
data:
  MYSQL_USER: bXl1c2Vy          # Base64 encoded value of "myuser"
  MYSQL_PASSWORD: bXktc2VjcmV0   # Base64 encoded value of "my-secret"