apiVersion: v1
kind: ServiceAccount
metadata:
  name: clo835
  namespace: final
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:eks:us-east-1:860572194478:cluster/group6-final-project-eks
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ebs-access-sa
  namespace: final
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::860572194478:role/LabRole
